name: dbt_demo
version: '1.0'
config-version: 2

profile: pass_snwflk_demo

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  pass_snwflk_demo:
    staging:
      +materialized: table
      +schema: analytics
    marts:
      +materialized: view
      +schema: analytics
