name: Snowflake DBT models

on:
    push:
        branches:
            - main
    # Allow to run this workflow manually from the Actions Tab
    workflow_dispatch:

jobs:
    dbt-ci-jobs:
        runs-on: ubuntu-latest
        environment: uat
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Installing Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
    
            - name: Make Script Executable
              run: chmod +x scritps/setup_dbt_env.sh
            
            - name: Create Python Virtual Environment and install DBT
              run: ./scritps/setup_dbt_env.sh

            - name: List files in the repository
              run: |
               ls ${{ github.workspace }}
              
            - name: Run DBT model with debug
              run: |
               cd ${{ github.workspace }}
               dbt run --select my_first_dbt_model

            - name: Pipeline status
              run: echo "the job status is ${{ job.status }}"
