name: Snowflake DBT models

on:
    push:
        branches:
            - main


jobs:
    dbt-ci-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Installing Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
    
            - name: Create Python Virtual Environment and install DBT
              run: ./setup_dbt_env.sh
              
            - name: Pipeline status
              run: echo "the job status is ${{ job.status }}"
