version: 2

sources:
  - name: analytics
    database: dbt_demo
    schema: analytics
    tables:
      - name: sales_data

models:
  - name: stg_sales_data
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: product_name
        data_tests:
          - not_null
          - unique
      - name: revenue
        data_tests:
          - not_null
          - greater_than: 0